// import { css } from '@emotion/react';
import Head from 'next/head';
import HeroImage from '../components/HeroImage';
import Layout from '../components/Layout';

// import heroPicture from '../public/images/bayc-mutant-hero.jpeg';

// const homePageSectionStyle = css`
//   background-image: url(${heroPicture});
// `;

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>N.F.T. Marketplace</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section>
        <HeroImage />
      </section>
      <section>Collection of the week</section>
    </Layout>
  );
}
