// import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/Layout';

// import heroPicture from '../public/images/bayc-mutant-hero.jpeg';

// const homePageSectionStyle = css`
//   background-image: url(${heroPicture});
// `;

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>N.F.T. Marketplace</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section>
        <Image
          src="/public/images/bayc-mutant-hero.jpeg"
          alt="Logo"
          width={1627}
          height={1028}
        />
        <h1>Best collection of NFTs</h1>
        <button>Buy Now</button>
      </section>
    </Layout>
  );
}
